version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.3-fpm
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "9000:9000"
    networks:
      - laravel-network
    environment:
      - TZ=Asia/Tokyo

  web:
    image: nginx:1.23
    container_name: laravel-web
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    networks:
      - laravel-network
    depends_on:
      - app

  node:
    image: node:20
    container_name: laravel-node
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel-network
    stdin_open: true
    tty: true

networks:
  laravel-network:
